# Generated by Django 5.1.5 on 2025-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_email_alter_customuser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
