# Generated by Django 5.1.5 on 2025-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="default_pic.png", upload_to=""
            ),
        ),
    ]
